In [ ]:
#Classificador MQO
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

size = 0.8
reps = 1
λ = 0.00000000000000000000000000001

data = np.loadtxt('../0b. DADOS/EMGsDataset.csv', delimiter=',')

C1, C2, C3, C4, C5 = 1, 2, 3, 4, 5
results = []
print(data)

[[0.000e+00 0.000e+00 9.050e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.430e+03 ... 0.000e+00 3.941e+03 3.938e+03]
 [1.000e+00 1.000e+00 4.000e+00 ... 1.000e+00 2.000e+00 2.000e+00]]


In [4]:
data = data.T
X = np.concatenate((
  data[data[:, 2] == C1, :2],
  data[data[:, 2] == C2, :2],
  data[data[:, 2] == C3, :2],
  data[data[:, 2] == C4, :2],
  data[data[:, 2] == C5, :2]
))

N, p = X.shape

X = np.concatenate((
  np.ones((N, 1)),
  X 
  ), axis = 1)

Y = np.concatenate((
  np.tile(np.array([[ 1,-1,-1,-1,-1]]), (10000, 1)),
  np.tile(np.array([[-1, 1,-1,-1,-1]]), (10000, 1)),
  np.tile(np.array([[-1,-1, 1,-1,-1]]), (10000, 1)),
  np.tile(np.array([[-1,-1,-1, 1,-1]]), (10000, 1)),
  np.tile(np.array([[-1,-1,-1,-1, 1]]), (10000, 1))
))

In [5]:
for _ in range(reps):
  indices = np.arange(N)
  np.random.shuffle(indices)
  
  ind_treino = indices[:int(N*size)]
  ind_teste = indices[int(N*size):]
  
  X_treino, X_teste = X[ind_treino], X[ind_teste]
  Y_treino, Y_teste = Y[ind_treino], Y[ind_teste]
  
  W = np.linalg.inv(X_treino.T@X_treino)@X_treino.T@Y_treino
  
  predict = X_teste@W
    
  res = []
    
  for i in range(predict.shape[0]):
    res.append(np.argmax(predict[i]) == np.argmax(Y_teste[i]))
  results.append(np.mean(res))
  
  
print("Média da Acurácia: ", np.mean(results))
print("Desvio Padrão: ", np.std(results))
print("Maior: ", np.max(results))
print("Menor: ", np.min(results))

Média da Acurácia:  0.726
Desvio Padrão:  0.0
Maior:  0.726
Menor:  0.726


In [6]:
# #Gráfico
# plt.scatter(data[data[:, 2] == C1, 0], data[data[:, 2] == C1, 1], color = 'red')
# plt.scatter(data[data[:, 2] == C2, 0], data[data[:, 2] == C2, 1], color = 'blue')
# plt.scatter(data[data[:, 2] == C3, 0], data[data[:, 2] == C3, 1], color = 'green')
# plt.scatter(data[data[:, 2] == C4, 0], data[data[:, 2] == C4, 1], color = 'yellow')
# plt.scatter(data[data[:, 2] == C5, 0], data[data[:, 2] == C5, 1], color = 'purple')